// gcc -dM -E - < /dev/null

#undef __SSP_STRONG__
#undef __DBL_MIN_EXP__
#undef __UINT_LEAST16_MAX__
#undef __ATOMIC_ACQUIRE
#undef __FLT128_MAX_10_EXP__
#undef __FLT_MIN__
#undef __GCC_IEC_559_COMPLEX
#undef __UINT_LEAST8_TYPE__ 
#undef __SIZEOF_FLOAT80__
#undef __INTMAX_C
#undef __CHAR_BIT__
#undef __UINT8_MAX__
#undef __SCHAR_WIDTH__
#undef __WINT_MAX__
#undef __FLT32_MIN_EXP__ 
#undef __ORDER_LITTLE_ENDIAN__
#undef __SIZE_MAX__
#undef __WCHAR_MAX__ 
#undef __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 
#undef __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 
#undef __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 
#undef __DBL_DENORM_MIN__ 
#undef __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 
#undef __GCC_ATOMIC_CHAR_LOCK_FREE 
#undef __GCC_IEC_559 
#undef __FLT32X_DECIMAL_DIG__ 
#undef __FLT_EVAL_METHOD__ 
#undef __FLT64_DECIMAL_DIG__ 
#undef __CET__ 
#undef __GCC_ATOMIC_CHAR32_T_LOCK_FREE 
#undef __UINT_FAST64_MAX__ 
#undef __SIG_ATOMIC_TYPE__ 
#undef __DBL_MIN_10_EXP__ 
#undef __FINITE_MATH_ONLY__ 
#undef __FLT32X_MAX_EXP__ 
#undef __FLT32_HAS_DENORM__ 
#undef __UINT_FAST8_MAX__ 
#undef __FLT32_MAX_10_EXP__ 
#undef __DEC64_MAX_EXP__ 
#undef __INT8_C
#undef __INT_LEAST8_WIDTH__ 
#undef __UINT_LEAST64_MAX__ 
#undef __SHRT_MAX__ 
#undef __LDBL_MAX__ 
#undef __FLT64X_MAX_10_EXP__ 
#undef __LDBL_IS_IEC_60559__
#undef __FLT64X_HAS_QUIET_NAN__ 
#undef __UINT_LEAST8_MAX__ 
#undef __GCC_ATOMIC_BOOL_LOCK_FREE 
#undef __FLT128_DENORM_MIN__ 
#undef __UINTMAX_TYPE__ 
#undef __linux 
#undef __DEC32_EPSILON__ 
#undef __FLT_EVAL_METHOD_TS_18661_3__ 
#undef __unix 
#undef __UINT32_MAX__ 
#undef __FLT128_MIN_EXP__ 
#undef __WINT_MIN__ 
#undef __FLT128_MIN_10_EXP__ 
#undef __FLT32X_IS_IEC_60559__ 
#undef __INT_LEAST16_WIDTH__ 
#undef __SCHAR_MAX__ 
#undef __FLT128_MANT_DIG__ 
#undef __WCHAR_MIN__ 
#undef __INT64_C
#undef __GCC_ATOMIC_POINTER_LOCK_FREE 
#undef __FLT32X_MANT_DIG__ 
#undef __USER_LABEL_PREFIX__ 
#undef __FLT64X_EPSILON__ 
//#undef __STDC_HOSTED__ 
#undef __DEC64_MIN_EXP__ 
#undef __DBL_DIG__ 
#undef __FLT32_DIG__
#undef __FLT_EPSILON__ 
#undef __SHRT_WIDTH__ 
#undef __FLT32_IS_IEC_60559__ 
#undef __LDBL_MIN__ 
//#undef __STDC_UTF_16__ 
#undef __DBL_IS_IEC_60559__ 
#undef __DEC32_MAX__
#undef __FLT64X_DENORM_MIN__ 
#undef __FLT32X_HAS_INFINITY__ 
#undef __INT32_MAX__ 
#undef __unix__ 
#undef __INT_WIDTH__ 
#undef __SIZEOF_LONG__ 
//#undef __STDC_IEC_559__ 
//#undef __STDC_ISO_10646__ 
#undef __UINT16_C
#undef __DECIMAL_DIG__ 
//#undef __STDC_IEC_559_COMPLEX__ 
#undef __FLT64_EPSILON__ 
#undef __gnu_linux__ 
#undef __FLT128_IS_IEC_60559__ 
#undef __FLT64X_MIN_10_EXP__ 
#undef __LDBL_HAS_QUIET_NAN__ 
#undef __FLT64_MANT_DIG__ 
#undef __FLT64X_MANT_DIG__ 
#undef __GNUC__ 
#undef __pie__
#undef __MMX__ 
#undef __FLT_HAS_DENORM__ 
#undef __SIZEOF_LONG_DOUBLE__ 
#undef __BIGGEST_ALIGNMENT__ 
#undef __FLT64_MAX_10_EXP__ 
#undef __DBL_MAX__ 
#undef __INT_FAST32_MAX__ 
#undef __DBL_HAS_INFINITY__ 
#undef __SIZEOF_FLOAT__ 
#undef __HAVE_SPECULATION_SAFE_VALUE 
#undef __DEC32_MIN_EXP__ 
#undef __INTPTR_WIDTH__ 
#undef __FLT64X_HAS_INFINITY__ 
#undef __UINT_LEAST32_MAX__ 
#undef __FLT32X_HAS_DENORM__ 
#undef __INT_FAST16_TYPE__
#undef __MMX_WITH_SSE__ 
#undef __LDBL_HAS_DENORM__ 
#undef __FLT128_HAS_INFINITY__ 
#undef __DEC32_MIN__ 
#undef __DBL_MAX_EXP__ 
#undef __WCHAR_WIDTH__ 
#undef __FLT32_MAX__ 
#undef __DEC128_EPSILON__ 
#undef __SSE2_MATH__ 
#undef __ATOMIC_HLE_RELEASE 
#undef __PTRDIFF_MAX__ 
#undef __amd64 
#undef __ATOMIC_HLE_ACQUIRE 
#undef __LONG_LONG_MAX__
#undef __SIZEOF_SIZE_T__ 
#undef __FLT64X_MIN_EXP__
#undef __SIZEOF_WINT_T__ 
#undef __LONG_LONG_WIDTH__ 
#undef __FLT32_MAX_EXP__ 
#undef __GXX_ABI_VERSION 
#undef __FLT_MIN_EXP__
#undef __GCC_HAVE_DWARF2_CFI_ASM 
#undef __INT16_MAX__ 
#undef __x86_64 
#undef __INT_FAST64_TYPE__ 
#undef __FLT64_DENORM_MIN__ 
#undef __DBL_MIN__ 
#undef __FLT128_EPSILON__ 
#undef __FLT64X_NORM_MAX__ 
#undef __SIZEOF_POINTER__ 
#undef __LP64__ 
#undef __DBL_HAS_QUIET_NAN__ 
#undef __FLT32X_EPSILON__ 
#undef __DECIMAL_BID_FORMAT__ 
#undef __FLT64_MIN_EXP__ 
#undef __FLT64_MIN_10_EXP__ 
#undef __FLT64X_DECIMAL_DIG__ 
#undef __DEC128_MIN__ 
#undef __REGISTER_PREFIX__ 
#undef __UINT16_MAX__ 
#undef __DBL_HAS_DENORM__ 
#undef __LDBL_HAS_INFINITY__ 
#undef __FLT32_MIN__ 
#undef __UINT8_TYPE__ 
#undef __FLT_DIG__ 
#undef __NO_INLINE__ 
#undef __DEC_EVAL_METHOD__ 
#undef __DEC128_MAX__ 
#undef __FLT_MANT_DIG__ 
#undef __LDBL_DECIMAL_DIG__ 
#undef __VERSION__ 
#undef __UINT64_C
#undef _STDC_PREDEF_H 
#undef __INT_LEAST32_MAX__ 
#undef __GCC_ATOMIC_INT_LOCK_FREE 
#undef __FLT128_MAX_EXP__ 
#undef __FLT32_MANT_DIG__ 
#undef __FLOAT_WORD_ORDER__
//#undef __STDC_IEC_60559_COMPLEX__ 
#undef __FLT128_HAS_DENORM__ 
#undef __FLT32_DECIMAL_DIG__ 
#undef __FLT128_DIG__ 
#undef __INT32_C
#undef __DEC64_EPSILON__ 
#undef __ORDER_PDP_ENDIAN__ 
#undef __DEC128_MIN_EXP__
#undef __INT_FAST32_TYPE__ 
#undef __UINT_LEAST16_TYPE__ 
#undef unix 
#undef __SIZE_TYPE__ 
#undef __UINT64_MAX__ 
#undef __FLT_IS_IEC_60559__ 
#undef __GNUC_WIDE_EXECUTION_CHARSET_NAME 
#undef __FLT64X_DIG__ 
#undef __INT8_TYPE__ 
#undef __ELF__ 
#undef __GCC_ASM_FLAG_OUTPUTS__ 
#undef __UINT32_TYPE__ 
#undef __FLT_RADIX__ 
#undef __INT_LEAST16_TYPE__ 
#undef __LDBL_EPSILON__ 
#undef __UINTMAX_C
#undef __SSE_MATH__ 
#undef __k8 
#undef __FLT32X_MIN__ 
#undef __SIG_ATOMIC_MAX__ 
#undef __GCC_ATOMIC_WCHAR_T_LOCK_FREE 
//#undef __STDC_IEC_60559_BFP__ 
#undef __SIZEOF_PTRDIFF_T__ 
#undef __LDBL_DIG__ 
#undef __FLT64_IS_IEC_60559__
#undef __x86_64__ 
#undef __FLT32X_MIN_EXP__
#undef __DEC32_SUBNORMAL_MIN__ 
#undef __INT_FAST16_MAX__ 
#undef __FLT64_DIG__ 
#undef __UINT_FAST32_MAX__ 
#undef __UINT_LEAST64_TYPE__ 
#undef __FLT_HAS_QUIET_NAN__ 
#undef __FLT_MAX_10_EXP__ 
#undef __LONG_MAX__ 
#undef __FLT64X_HAS_DENORM__ 
#undef __DEC128_SUBNORMAL_MIN__ 
#undef __FLT_HAS_INFINITY__ 
#undef __GNUC_EXECUTION_CHARSET_NAME 
#undef __UINT_FAST16_TYPE__ 
#undef __DEC64_MAX__ 
#undef __INT_FAST32_WIDTH__ 
#undef __CHAR16_TYPE__ 
#undef __PRAGMA_REDEFINE_EXTNAME 
#undef __SIZE_WIDTH__ 
#undef __SEG_FS 
#undef __INT_LEAST16_MAX__ 
#undef __DEC64_MANT_DIG__ 
#undef __INT64_MAX__ 
#undef __SEG_GS 
#undef __FLT32_DENORM_MIN__ 
#undef __SIG_ATOMIC_WIDTH__ 
#undef __INT_LEAST64_TYPE__ 
#undef __INT16_TYPE__ 
#undef __INT_LEAST8_TYPE__ 
//#undef __STDC_VERSION__ 
#undef __SIZEOF_INT__ 
#undef __DEC32_MAX_EXP__ 
#undef __INT_FAST8_MAX__ 
#undef __FLT128_MAX__ 
#undef __INTPTR_MAX__ 
#undef linux 
#undef __FLT64_HAS_QUIET_NAN__ 
#undef __FLT32_MIN_10_EXP__ 
#undef __FLT32X_DIG__ 
#undef __PTRDIFF_WIDTH__ 
#undef __LDBL_MANT_DIG__ 
#undef __FLT64_HAS_INFINITY__ 
#undef __FLT64X_MAX__ 
#undef __SIG_ATOMIC_MIN__ 
#undef __code_model_small__ 
#undef __GCC_ATOMIC_LONG_LOCK_FREE 
#undef __DEC32_MANT_DIG__ 
#undef __k8__ 
#undef __INTPTR_TYPE__ 
#undef __UINT16_TYPE__ 
#undef __WCHAR_TYPE__ 
#undef __pic__ 
#undef __UINTPTR_MAX__ 
#undef __INT_FAST64_WIDTH__ 
#undef __INT_FAST64_MAX__ 
#undef __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 
#undef __FLT_NORM_MAX__ 
#undef __FLT32_HAS_INFINITY__ 
#undef __FLT64X_MAX_EXP__ 
#undef __UINT_FAST64_TYPE__ 
#undef __INT_MAX__ 
#undef __linux__ 
#undef __INT64_TYPE__ 
#undef __FLT_MAX_EXP__ 
#undef __ORDER_BIG_ENDIAN__ 
#undef __DBL_MANT_DIG__ 
#undef __SIZEOF_FLOAT128__ 
#undef __INT_LEAST64_MAX__ 
#undef __GCC_ATOMIC_CHAR16_T_LOCK_FREE 
#undef __DEC64_MIN__ 
#undef __WINT_TYPE__ 
#undef __UINT_LEAST32_TYPE__ 
#undef __SIZEOF_SHORT__ 
#undef __FLT32_NORM_MAX__ 
#undef __SSE__ 
#undef __LDBL_MIN_EXP__ 
#undef __FLT64_MAX__ 
#undef __amd64__ 
#undef __WINT_WIDTH__ 
#undef __INT_LEAST8_MAX__ 
#undef __INT_LEAST64_WIDTH__ 
#undef __LDBL_MAX_EXP__ 
#undef __FLT32X_MAX_10_EXP__ 
#undef __SIZEOF_INT128__ 
#undef __FLT64X_IS_IEC_60559__ 
#undef __LDBL_MAX_10_EXP__ 
#undef __ATOMIC_RELAXED 
#undef __DBL_EPSILON__ 
#undef __FLT128_MIN__ 
#undef _LP64 
#undef __UINT8_C
#undef __FLT64_MAX_EXP__ 
#undef __INT_LEAST32_TYPE__ 
#undef __SIZEOF_WCHAR_T__ 
#undef __UINT64_TYPE__
#undef __GNUC_PATCHLEVEL__ 
#undef __FLT128_NORM_MAX__ 
#undef __FLT64_NORM_MAX__ 
#undef __FLT128_HAS_QUIET_NAN__ 
#undef __INTMAX_MAX__ 
#undef __INT_FAST8_TYPE__ 
#undef __FLT64X_MIN__
#undef __GNUC_STDC_INLINE__ 
#undef __FLT64_HAS_DENORM__ 
#undef __FLT32_EPSILON__ 
#undef __DBL_DECIMAL_DIG__ 
//#undef __STDC_UTF_32__ 
#undef __INT_FAST8_WIDTH__ 
#undef __FXSR__ 
#undef __FLT32X_MAX__
#undef __DBL_NORM_MAX__ 
#undef __BYTE_ORDER__ 
#undef __INTMAX_WIDTH__ 
#undef __UINT32_C
#undef __FLT_DENORM_MIN__ 
#undef __INT8_MAX__ 
#undef __LONG_WIDTH__ 
#undef __PIC__ 
#undef __UINT_FAST32_TYPE__ 
#undef __FLT32X_NORM_MAX__ 
#undef __CHAR32_TYPE__ 
#undef __FLT_MAX__ 
#undef __SSE2__ 
#undef __INT32_TYPE__ 
#undef __SIZEOF_DOUBLE__ 
#undef __FLT_MIN_10_EXP__ 
#undef __FLT64_MIN__ 
#undef __INT_LEAST32_WIDTH__ 
#undef __INTMAX_TYPE__ 
#undef __DEC128_MAX_EXP__ 
#undef __FLT32X_HAS_QUIET_NAN__ 
#undef __ATOMIC_CONSUME 
#undef __GNUC_MINOR__ 
#undef __INT_FAST16_WIDTH__ 
#undef __UINTMAX_MAX__ 
#undef __PIE__ 
#undef __FLT32X_DENORM_MIN__ 
#undef __DBL_MAX_10_EXP__ 
#undef __LDBL_DENORM_MIN__ 
#undef __INT16_C
//#undef __STDC__ 
#undef __PTRDIFF_TYPE__
#undef __ATOMIC_SEQ_CST 
#undef __FLT32X_MIN_10_EXP__
#undef __UINTPTR_TYPE__ 
#undef __DEC64_SUBNORMAL_MIN__ 
#undef __DEC128_MANT_DIG__ 
#undef __LDBL_MIN_10_EXP__ 
#undef __SIZEOF_LONG_LONG__ 
#undef __FLT128_DECIMAL_DIG__ 
#undef __GCC_ATOMIC_LLONG_LOCK_FREE 
#undef __FLT32_HAS_QUIET_NAN__ 
#undef __FLT_DECIMAL_DIG__ 
#undef __UINT_FAST16_MAX__ 
#undef __LDBL_NORM_MAX__ 
#undef __GCC_ATOMIC_SHORT_LOCK_FREE 
#undef __UINT_FAST8_TYPE__ 
#undef __ATOMIC_ACQ_REL 
#undef __ATOMIC_RELEASE 
